name:       GraficasEnIHaskell
version:    '0.1.0.0'
synopsis:   Represenci칩n de gr치ficas con GNUplot en IHaskell.
category:   Educational
author:     Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright:  Jose A. Alonso
license:    BSD3
github:     jaalonso/GraficasEnIHaskell
description: >
  Represenci칩n de gr치ficas con GNUplot en IHaskell.

extra-source-files:
- README.org

dependencies:
- base >= 4.7 && < 5
- gnuplot
- ihaskell
- ihaskell-gnuplot


